import NFT7 from "../utils/Abis/NFT7.json";
import WETH from "../utils/Abis/WETH.json";
import NFT11 from "../utils/Abis/NFT11.json";
import NFT13 from "../utils/Abis/NFT13.json";
import Resale from "../utils/Abis/Resale.json";

export const devConfiguration = {
	baseShareUrl: "http://quytech.in:3327/",
	baseUrl: "http://quytech.in:8008/api/V1",
	getRole: "/role",
	registerClient: "/user",
	logout: "/disconnect",
	getUserProfile: "/Profile",
	getUserOwned: "/ownedNft",
	updateRefreshToken: "/refreshToken",
	updateUserProfile: "/user-profile",
	registerCreator: "/register-creator",
	updateCreator: "/creator",
	getTerms: "/getTermsAndCondition",
	getPrivacyPolicy: "/getPrivacyPolicy",
	getHelp: "/getHelpAndGuidance",
	getFaq: "/getFaq",
	getTypology: "/listOfTypology",
	getFeaturedCollection: "/listOfFeaturedCollection",
	getFeature: "/listOfFeaturedCreators",
	getFeaturedNft: "/listOfFeaturedNfts",
	getAllCreator: "/listOfAllCreators",
	getAllCollection: "/listOfAllCollection",
	addNft: "/nft",
	editNft: "/nft",
	getAllMarketPlace: "/list-all-marketplace",
	getCollectionDetail: "/listNftInCollection?collection_id=",
	getTypology: "/listOfTypology",
	getCollection: "/userCollection",
	getNFTDetails: "/nft-data?id=",
	postReport: "/addReport",
	setNewsletter: "/addNewsLetter",
	getBannerImage: "/bannerImage",
	getSearch: "/search?search=",
	getActivity: "/activity",
	getCreatorRank: "/creatorRanking?duration",
	getOwnedNft: "/ownedNft",
	getFavoritedNft: "/listOfFavouriteNft",
	getTypologySearch: "/searchTypology",
	sellNFT: "/sale-nft",
	getCommision: "/comission",
	getLikeStatus: "/checkFavourite?",
	addFav: "/addFavourite",
	uploadIpfs: "/ipfs",
	getNftOfCreator: "/getNftOfCreator",
	getCreatorData: "/getNftOfCreator?creator_id=",
	marketPlaceFilter: "/list-all-marketplace",
	addZip: "/zip",
	getUSDPrice: "/USDPrice?symbol=",
	updateViewCount: "/view",
	onSaleApi: "/onSale",
	soldApi: "/sold",
	getCreatorActivity: "/creatorActivity",
	deleteNFT: "/nftDelete",
	editNftPrice: "/price",
	getFloorPriceCreator: "/creatorData",
	creatorFilter: "/filter",
	getCreatorCalc: "/creatorData",
	getNotification: "/allnotifications",
	getClearAllNotification: "/clearAllNotifications",
	deleteNotification: "/deleteNotification",
	getCollectionInfo: "/collectionDetails?id=",
	collectionFilter: "/listNftInCollection?collection_id=",
	getCollectionTotal: "/colllectionData",
	updateVoucher: "/signature",
	purchaseNFT: "/purchase",
	getListing: "/listing?token_count=",
	placeBid: "/placeBid",
	getBid: "/listOfBid?token_id=",
	acceptBid: "/acceptBid",
	addCustomeProperties: "/addCustomeProperties",
	featuredTypology: "/listOfFeaturedTypology",
	checkExpiredNftSale: "/checkExpiredNftSale",
	removeCreatorNft: "/removeNft",
	cancelNft: "/removeFromSale",
	searchCustomProps: "/searchCustomProperties",
};
export const devAbiConfig = {
	nft7: NFT7,
	nft11: NFT11,
	nft13: NFT13,
	resale: Resale,
	weth: WETH,
	chainId: 80001,
	// nftAddress: '0xec64274e505a47559570d81bc91b340a16dc3305',
	nftAddress: '0x0CA19516cC49e7744e8E60364Dd4DbEED7E7d5E1',
	// nftAddress: "0x125bb09BA2E684995948E8834Cde430E2CE2dFfC",

	resaleAddress: "0x71A0f7E1825F5aaFEcB87F18e1D41F2b8F0E713F",
	zeroAddress: "0x0000000000000000000000000000000000000000",
	tokenAddress: "0xf4555e485d6575Edf3D255d52b2f51dE8529c39c",
};
