import NFT7 from "../utils/Abis/NFT7.json";
import WETH from "../utils/Abis/WETH.json";
import NFT13 from "../utils/Abis/NFT13.json";
import Resale from "../utils/Abis/Resale.json";

export const prodConfiguration = {
  baseShareUrl: "http://quytech.in:3327/",
  baseUrl: "http://quytech.in:8008/api/V1",
  getRole: "/role",
  registerClient: "/user",
  logout: "/disconnect",
  getUserProfile: "/Profile",
  updateRefreshToken: "/refreshToken",
  updateUserProfile: "/user-profile",
  registerCreator: "/register-creator",
  updateCreator: "/creator",
  getTerms: "/getTermsAndCondition",
  getPrivacyPolicy: "/getPrivacyPolicy",
  getHelp: "/getHelpAndGuidance",
  getFaq: "/getFaq",
  getTypology: "/listOfTypology",
  getFeaturedCollection: "/listOfFeaturedCollection",
  getFeature: "/listOfFeaturedCreators",
  getFeaturedNft: "/listOfFeaturedNfts",
  getAllCreator: "/listOfAllCreators?search",
  getAllCollection: "/listOfAllCollection",
  addNft: "/nft",
  editNft: "/nft",
  getAllMarketPlace: "/list-all-marketplace",
  getCollectionDetail: "/listNftInCollection?collection_id=",
  getTypology: "/listOfTypology",
  getCollection: "/collection",
  getNFTDetails: "/nft-data?id=",
  getActivity: "/activity",
  postReport: "/addReport",
  setNewsletter: "/addNewsLetter",
  getBannerImage: "/bannerImage",
  getSearch: "/search?search=",
  getCreatorRank: "/creatorRanking?duration",
  getOwnedNft: "/ownedNft",
  getFavoritedNft: "/listOfFavouriteNft",
  getTypologySearch: "/searchTypology",
  sellNFT: "/sale-nft",
  getCommision: "/comission",
  getLikeStatus: "/checkFavourite?",
  addFav: "/addFavourite",
  uploadIpfs: "/ipfs",
  getNftOfCreator: "/getNftOfCreator",
  getCreatorData: "/getNftOfCreator?creator_id=",
  marketPlaceFilter: "/list-all-marketplace",
  addZip: "/zip",
  onSaleApi: "/onSale",
  soldApi: "/sold",
  getCreatorActivity: "/creatorActivity",
  getUSDPrice: "/USDPrice?symbol=",
  updateViewCount: "/view",
  deleteNFT: "/nftDelete",
  editNftPrice: "/price",
  getFloorPriceCreator: "/creatorData",
  creatorFilter: "/filter",
  getCreatorCalc: "/creatorData",
  getNotification: "/allnotifications",
  getClearAllNotification: "/clearAllNotifications",
  deleteNotification: "/deleteNotification",
  getCollectionInfo: "/collectionDetails?id=",
  collectionFilter: "/listNftInCollection?collection_id=",
  getCollectionTotal: "/colllectionData",
  updateVoucher: "/signature",
  purchaseNFT: "/purchase",
  getListing: "/listing?token_count=",
  featuredTypology: "/listOfFeaturedTypology",
  checkExpiredNftSale: "/checkExpiredNftSale",
  removeCreatorNft: "/removeNft",
  cancelNft: "/removeFromSale",
  searchCustomProps: "/searchCustomProperties",
};

export const prodAbiConfig = {
  nft7: NFT7,
  nft13: NFT13,
  resale: Resale,
  weth: WETH,
  chainId: 80001,
  // nftAddress: "0xc4aa2f24e7e35287cddafde6fea1be7da5bd8867",
  nftAddress: "0x0CA19516cC49e7744e8E60364Dd4DbEED7E7d5E1",
  // nftAddress: "0x125bb09BA2E684995948E8834Cde430E2CE2dFfC",
  resaleAddress: "0x71A0f7E1825F5aaFEcB87F18e1D41F2b8F0E713F",
  zeroAddress: "0x0000000000000000000000000000000000000000",
  tokenAddress: "0xf4555e485d6575Edf3D255d52b2f51dE8529c39c",
};
